# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endusers',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
