# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_id', models.CharField(default='sc_test', max_length=20, unique=True)),
                ('sub_category_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='categories',
            name='name',
        ),
        migrations.AddField(
            model_name='categories',
            name='category_id',
            field=models.CharField(default='C_test', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='category_name',
            field=models.CharField(default='test', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category_id',
            field=models.CharField(default='sc_test', max_length=20, unique=True),
        ),
    ]
