# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170812_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories',
            name='category_id',
            field=models.ForeignKey(default='c_test', on_delete=django.db.models.deletion.CASCADE, to='products.Categories'),
        ),
    ]
