# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_subcategories_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='sub_category_name',
            field=models.CharField(max_length=200),
        ),
    ]
