# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20170812_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories',
            name='name',
            field=models.CharField(default='test', max_length=200),
        ),
    ]
