# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_subcategories_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='id',
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_id',
            field=models.CharField(default='C_test', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
