# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20170812_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categoryset', to='products.Categories'),
        ),
    ]
