# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20170813_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='product_details',
            new_name='product',
        ),
    ]
