# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20170813_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategories',
            name='id',
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='sub_category_id',
            field=models.CharField(default='sc_test', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
