# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20170813_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='images',
            field=models.ImageField(null=True, upload_to='static/images/categories'),
        ),
    ]
