# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20170813_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='images',
            field=models.ImageField(null=True, upload_to='products/static/products/images/categories'),
        ),
    ]
