# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20170813_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='images',
            new_name='image',
        ),
    ]
